### ISSUE TITLE
Add winget installation options

### ISSUE THREAD

**Issue by OhMyMndy** [canonical/multipass.run#266]
Hi!

I wanted to create a pull request to update the documentation to include the command which can be used to install **Multipass** and **[Sysinternals](https://docs.microsoft.com/en-gb/sysinternals/#whats-new-october-14-2021)** through **[winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/)**.

https://multipass.run/docs/set-up-the-driver#heading--install-virtualbox-windows
Here `winget install --id Oracle.VirtualBox` can be added as an installation option.

https://multipass.run/docs/set-up-the-driver#heading--use-virtualbox-to-view-multipass-instances-windows
Here `winget install sysinternals` can be added.
as well as
`PsExec.exe -s 'C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' list vms` (Default installation location when installing through `winget`

https://multipass.run/docs/installing-on-windows#heading--install-upgrade-uninstall
Here `winget install --id Canonical.Multipass` can be added as installation option.

If I can create a pull request for it, feel free to point me to the location where I can change the templates/markdown files.

Thanks for this awesome tool!

**Comment by petesfrench** [comment]
@evilnick can you take a look at this please

**Comment by Saviq** [comment]
CC @townsend2010

**Comment by anthonydillon** [comment]
@tmihoc could you help here? Would this be content you would like to add to the documentation? Or show @OhMyMndy how to do it?

**Comment by tmihoc** [comment]
@OhMyMndy @anthonydillon To update these Multipass website pages, one needs to edit the corresponding Discourse, or comment on the corresponding Discourse to suggest the edits to the Multipass team. The Discourse for the pages mentioned above are:

- https://discourse.ubuntu.com/t/how-to-set-up-the-driver/28701?_ga=2.237694594.38070369.1662543241-682440666.1657543238#heading--install-virtualbox-windows

- https://discourse.ubuntu.com/t/how-to-set-up-the-driver/28701?_ga=2.237694594.38070369.1662543241-682440666.1657543238#heading--use-virtualbox-to-view-multipass-instances-windows

- https://discourse.ubuntu.com/t/how-to-install-multipass-on-windows/9547?_ga=2.68874003.38070369.1662543241-682440666.1657543238#heading--install-upgrade-uninstall

@townsend2010 maybe @luis4a0 or someone else on the Multipass team could review the additions?

**Comment by townsend2010** [comment]
We can address any suggestions to the documentation as it comes in as @tmihoc pointed out.

**Comment by sowasred2012** [comment]
As pointed out, any changes can be suggested on the discourse posts - closing.
