### ISSUE TITLE
Update navigation with new logo

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/multipass.run#271]
The logo can be found here: https://assets.ubuntu.com/v1/4f762974-Canonical+Multipass.svg
@nathan-j-hart This is where you ca nkeep an eye on the progress with this.

for reference: https://maas.io/#navigation

**Comment by nathan-j-hart** [comment]
FYI @townsend2010

**Comment by petesfrench** [comment]
@lyubomir-popov Will we not need the inverted version of this image to go over the dark navigation of multipass.run?

**Comment by nathan-j-hart** [comment]
@petesfrench here is the issue I was emailing about earlier. It would be great to get this in the queue.

**Comment by nathan-j-hart** [comment]
Hi team, I was on the website today and saw that the new logo was up. Thanks for that. It would be great if we could at least also change the large logo at the top of the page, it is currently a bit confusing to see both logos displayed simultaneously. If more work needs to happen to get that done I would prefer to roll back so we don't have this halfway done.
![image](https://user-images.githubusercontent.com/77587653/215839264-4e3a4056-5bdf-4f66-8720-18295d4b30a7.png)
