### ISSUE TITLE
What is the default driver for Linux?

### ISSUE THREAD

**Issue by mkgvt** [canonical/multipass.run#272]
According to [the main page](https://multipass.run/), Linux uses LXD. But according to [the driver setup page](https://multipass.run/docs/set-up-the-driver) it uses Qemu by default but can be switched to libvirt. The two pages seem to be inconsistent.

**Comment by mtruj013** [comment]
Hi @mkgvt! Could you please raise this issue on the [multipass repo](https://github.com/canonical/multipass/issues/new)? This is the one for the website. Thanks!

**Comment by townsend2010** [comment]
Hmm, well, this isn't really a Multipass issue.  The website isn't fully correct.  Multipass uses QEMU by default on x86_64 Linux, but uses LXD by default on all other supported Linux architectures.  To be honest, I'm not sure how that would messaged on the website though.

**Comment by mkgvt** [comment]
I suspected that which is why I posted here. But I opened the issue in the Multipass repo also.

Note: I'm using LXD directly but Multipass came to my attention. I noted the discrepancy while reading and thought I should report it.
