### ISSUE TITLE
Discourse docs are no longer working correctly

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass.run#310]
*Note - filling in this form will file an issue against the www.multipass.run website, not against Multipass itself, for Multipass bugs, please [go here](https://github.com/canonical/multipass)*

## Summary

`multipass.run/docs` is no longer working correctly.  The main page now shows `Navigation` and `Redirects` and clicking on links on the main page take you to the actual Discourse post.

## Process

Open multipass.run/docs.  Observe at the bottom "Navigation" and "Redirects".

Click on "Tutorials" on the main page and observe you are taken to 
https://discourse.ubuntu.com/t/tutorials/27140.

## Current and expected result

I expect not to see "Navigation" and "Redirects" and when clicking "Tutorials" to be taken to the docs website page, not Discourse.

**Comment by anthonydillon** [comment]
Thanks for the report. This has been fixed and released.
