### ISSUE TITLE
Add license information in docs footer

### ISSUE THREAD

**Issue by giuliazanchi** [canonical/multipass.run#330]
## Summary

Add Creative Commons license information to docs footer, as agreed with and approved by the Legal team.

## Current and expected result

We need to update the existing copyright notice in the footer of all pages under https://multipass.run/docs from:

* **© 2024 Canonical Ltd.**

to:

* **Copyright © 2024
  CC-BY-SA, Canonical Ltd.**

For an example, see https://anbox-cloud.io/ vs. https://anbox-cloud.io/docs . 
See also https://github.com/canonical/anbox-cloud.io/pull/338/files for the practical update that was done.

## Screenshot

Current footer:
<img width="1332" alt="Screenshot 2024-07-02 at 14 56 45" src="https://github.com/canonical/multipass.run/assets/8100355/1cdbf895-0486-453b-a0d9-2cbcfb714b70">

**Comment by britneywwc** [comment]
Thanks! Closing this as it has been resolved in PR #331
